### ISSUE TITLE
2.68.0 changes DefaultFilter API?

### ISSUE THREAD

**Issue by davewichers** [HtmlUnit/htmlunit-neko#17]
When I upgrade to 2.68.0 my project, AntiSamy (https://github.com/nahsra/antisamy), now gets a build error that I didn't get with 2.67.0 and prior. I notice a major change was made in 2.68.0 per the README: "As of version 2.68.0, neko-htmlunit also uses its own fork of Xerces (https://github.com/apache/xerces2-j). This made it possible to remove many unneeded parts and dependencies to ensure e.g. compatibility with Android."  <-- The end of this sentence is a bit awkward by the way.

When I upgrade to 2.68.0, I get the following build error:

antisamy_main/src/main/java/org/owasp/validator/html/scan/MagicSAXFilter.java:[54,8] org.owasp.validator.html.scan.MagicSAXFilter is not abstract and does not override abstract method getDocumentSource() in org.apache.xerces.xni.XMLDocumentHandler

The code in question is here: https://github.com/nahsra/antisamy/blob/main/src/main/java/org/owasp/validator/html/scan/MagicSAXFilter.java

The class declaration is: public class MagicSAXFilter extends net.sourceforge.htmlunit.cyberneko.filters.DefaultFilter implements org.apache.xerces.xni.parser.XMLDocumentFilter {

I'm guessing that the net.sourceforge.htmlunit.cyberneko.filters.DefaultFilter API changed somehow? Or did the org.apache.xerces.xni.parser.XMLDocumentFilter API change?

Any suggestions on how to deal with this? Do I need to change another import in my pom? Which is here: https://github.com/nahsra/antisamy/blob/main/pom.xml

I don't see anything in the README that says, when you upgrade to 2.68.0, you also need to upgrade to version X of something, or change your import of Y to Z. Is this any undocumented API change or am I doing something wrong?

Thanks, Dave

**Comment by rbri** [comment]
Hi @davewichers ,

sorry for that. I was a bit lazy about backward compatibility because i my feeling was, neko is only used from HtmlUnit.
Will have a look and then come back to you.

**Comment by rbri** [comment]
ok first step done - i can build and run the tests for antisamy

**Comment by rbri** [comment]
ok, looks more or less simple

neko-htmlunit still contains copies of some of the required classes - only with a different package name (and step by step some code cleanup). You only have to fix the  imports of your code...

Please replace all occurrences of 

    import org.apache.xerces.

with

    import net.sourceforge.htmlunit.xerces.

and you are done (hopefully).

**Comment by rbri** [comment]
btw made a quick test with 2.69.0 and this also works

and if you like to get rid of xerces at all there is also https://github.com/HtmlUnit/htmlunit-cssparser that might implement a more recent version of css. But changing this will be a bigger issue for your code.

**Comment by davewichers** [comment]
That seems to mostly work. However, when I drop the import of xerces from my pom, I now get this error: AbstractAntiSamyScanner.java:[33,32] package org.apache.xml.serialize does not exist. <--

And I checked to see if xerces has other dependencies it brings in and it does not. So maybe you need to add serialize to your version of xerces?

Apparently this API is built into the xerces JAR per: https://stackoverflow.com/questions/13438072/the-import-org-apache-xml-serialize-xmlserializer-cannot-be-resolved. The API is described here: https://xerces.apache.org/xerces-j/apiDocs/org/apache/xml/serialize/package-summary.html and you'll notice its part of the Xerces documentation.

Also, when this is all done and working properly, can you update your readme with the import changes required to get 2.68.0 to work IF they are directly using any of the original org.apache.xerces code? And also tell them to remember to drop the import of xerces:xercesImpl.

**Comment by rbri** [comment]
Maybe you assumption is a bit wrong - neko-html no longer uses xerces. This mean you can use neko-htmlunit without having xerces in your project.
But your project uses Xerces directly - if you like to get rid of this dependency you have to find a replacement for the xerces functionality in use or write your own. In your case this is the (deprecated) Serializer.

**Comment by rbri** [comment]
Or some more detailed:

MagicSAXFilter -this class uses the filter stuff from neko - you have to change the import here.

AntiSamySAXScanner - this does not really use neko stuff if you replace 

    XMLDocumentFilter[] filters = {magicSAXFilter};

by 

    MagicSAXFilter[] filters = {magicSAXFilter};

then you can rid of one more import.

AntiSamyDOMScanner - this uses a default dom implementation - you can use the one that is still in the neko package.

The tricky part is the use of org.apache.xml.serialize.HTMLSerializer and org.apache.xml.serialize.HTMLSerializer. This is Xerces core functionality directly used by your application - nothing that neko ever has provided.
So you have to find your own replacement.

Regarding HTMLSerializer there is a hint in the javadoc - This class was deprecated in Xerces 2.6.2. It is recommended that new applications use JAXP's Transformation API  for XML (TrAX) for serializing HTML. See the Xerces documentation for more information.

**Comment by davewichers** [comment]
Thanks for the tips/advice here. What exactly do you mean by:
"AntiSamyDOMScanner - this uses a default dom implementation - you can use
the one that is still in the neko package." Are there classes I'm using now
that I can simply replace with classes provided with the Neko HTML Unit
library? If so, is it simply a drop in replacement? I.e., replace use of X
with Y? Any more guidance on how to implement that chance would
be appreciated.

**Comment by rbri** [comment]
@davewichers 

Had another look at your commit https://github.com/nahsra/antisamy/commit/db549ac8a203988f957b00635a44f46e87b76aca. form me this looks fine. With this the update to the latest htmlunit-neko is done / correct.
